name: Python application
on:
  pull_request:
    branches: [homework3, homework7]
jobs:
  PytestHomework:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/homework3' ||
        github.ref == 'refs/heads/homework7'
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest ${{ steps.extract_branch.outputs.branch }} -n 2
