name: Selenium Homework
on:
  pull_request:
    branches: [homework1, homework2]
jobs:
  SeleniumHomework:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/homework1'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Install chromedriver locally
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: '98.0.4758.102'
      - name: Test with pytest
        run: |
          pytest ${{ steps.extract_branch.outputs.branch }} -n2 --headless
