name: Template sync
on:
  schedule:
  - cron: "*/2 * * * *"
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: sync
        uses: AndreasAugustin/actions-template-sync@v0.4.1-draft
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: VK-Education-Python-automation/template-repository
